### ISSUE TITLE
Add a picture for the recovered state

### ISSUE THREAD

**Issue by holke** [Davknapp/WirvsVirus#24]
Humans can have the state "recovered". Currently the symbol used is the same as for "Healthy" but it should be something different.

**Comment by Raggiegandalf** [comment]
Maybe something that shows, that they are also immune to another infection? Could be something like a Helmet or anything.. maybe a shield

**Comment by maccxs** [comment]
Added a recoverered and dead smiley with  e3ffbb7fa4d7677c773baea62924bbd3c9e49e05
